
const vehicleMakersModels: { [key: string]: string[] } = {
    "Acura": ["ILX", "MDX", "RDX", "RLX", "NSX"],
    "Alfa Romeo": ["Giulia", "Stelvio", "4C", "Tonale"],
    "Audi": ["A3", "A4", "A6", "Q5", "Q7"],
    "BMW": ["3 Series", "5 Series", "7 Series", "X3", "X5"],
    "Buick": ["Enclave", "Encore", "LaCrosse", "Regal", "Verano"],
    "Chevrolet": ["Cruze", "Malibu", "Silverado", "Suburban", "Tahoe"],
    "Dodge": ["Challenger", "Charger", "Durango", "Grand Caravan", "Journey"],
    "Ford": ["Escape", "Explorer", "F-150", "Focus", "Mustang"],
    "Honda": ["Accord", "Civic", "CR-V", "Fit", "Pilot"],
    "Hyundai": ["Elantra", "Kona", "Santa Fe", "Sonata", "Tucson"],
    "Jaguar": ["E-PACE", "F-PACE", "I-PACE", "XE", "XF"],
    "Jeep": ["Cherokee", "Compass", "Grand Cherokee", "Renegade", "Wrangler"],
    "Kia": ["Optima", "Soul", "Sorento", "Sportage", "Telluride"],
    "Land Rover": ["Defender", "Discovery", "Evoque", "Range Rover", "Velar"],
    "Lexus": ["ES", "IS", "LS", "NX", "RX"],
    "Mazda": ["CX-5", "CX-9", "Mazda3", "Mazda6", "MX-5 Miata"],
    "Mercedes-Benz": ["C-Class", "E-Class", "GLC", "GLE", "S-Class"],
    "Mitsubishi": ["Eclipse Cross", "Lancer", "Mirage", "Outlander", "Pajero"],
    "Nissan": ["Altima", "Maxima", "Murano", "Rogue", "Sentra"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan"],
    "Subaru": ["Crosstrek", "Forester", "Impreza", "Legacy", "Outback"],
    "Tesla": ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y"],
    "Toyota": ["Camry", "Corolla", "Highlander", "RAV4", "Tacoma"],
    "Volkswagen": ["Atlas", "Golf", "Jetta", "Passat", "Tiguan"],
    "Volvo": ["S60", "V60", "XC40", "XC60", "XC90"],
};

export default vehicleMakersModels